name: Auto-Deploy to Production  

on:  
  push:  
    branches:  
      - main  # Trigger on pushes to main branch  

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: deploy
